In [37]:
import pandas as pd

In [38]:
# Load the input data into a DataFrame
individual_df = pd.read_csv('biourja-efzrr-y7i38ed9-input.csv')
individual_df.columns = ['Plant_Name', 'Forecast', 'Capacity']

In [39]:
individual_df.head(10)

  Plant_Name  Forecast  Capacity
0         E1      45.4       100
1         E2      31.2       150
2         E3       8.5        50
3         E4      88.2       100
4         E5      98.4       150
5         E6     238.5       300
6         E7      66.8       100
7         E8     115.4       150
8         E9      74.0       100
9        E10     156.8       200

In [40]:
# Define the updated zonal level forecasts
zonal_forecasts = {
    'East': 2800,
    'North': 1500,
    'West': 2000,
    'South': 6500
}

In [41]:
# zonal_df is the dataframe that contains zone and their corresponding zonal forecast
zonal_df = pd.DataFrame(list(zonal_forecasts.items()), columns=['zone', 'forecast'])

In [42]:
zonal_df.head(5)

    zone  forecast
0   East      2800
1  North      1500
2   West      2000
3  South      6500

In [43]:
# Calculate the sum of all the forecasts
total_forecast = zonal_df['forecast'].sum()

# Modify the "forecast" column with the formula
zonal_df['forecast'] = (zonal_df['forecast'] * 12000) / total_forecast

zonal_df.head()

    zone  forecast
0   East   2625.00
1  North   1406.25
2   West   1875.00
3  South   6093.75

In [44]:
# Separating the individual wind farm forecasts zone wise i.e. E1:E24, N1:N26, W1:W15 and S1:S35
east_individual_dataframe = individual_df[individual_df['Plant_Name'].str.startswith('E')]
north_individual_dataframe = individual_df[individual_df['Plant_Name'].str.startswith('N')]
west_individual_dataframe = individual_df[individual_df['Plant_Name'].str.startswith('W')]
south_individual_dataframe = individual_df[individual_df['Plant_Name'].str.startswith('S')]

In [45]:
# Adding a new column "Weight" to each of the dataframes
east_individual_dataframe['Weight'] = east_individual_dataframe['Forecast'] / east_individual_dataframe['Capacity']
north_individual_dataframe['Weight'] = north_individual_dataframe['Forecast'] / north_individual_dataframe['Capacity']
west_individual_dataframe['Weight'] = west_individual_dataframe['Forecast'] / west_individual_dataframe['Capacity']
south_individual_dataframe['Weight'] = south_individual_dataframe['Forecast'] / south_individual_dataframe['Capacity']

C:\Users\prakhar\AppData\Local\Temp\ipykernel_11556\2047925684.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  east_individual_dataframe['Weight'] = east_individual_dataframe['Forecast'] / east_individual_dataframe['Capacity']
C:\Users\prakhar\AppData\Local\Temp\ipykernel_11556\2047925684.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  north_individual_dataframe['Weight'] = north_individual_dataframe['Forecast'] / north_individual_dataframe['Capacity']
C:\Users\prakhar\AppData\Local\Temp\ipykernel_11556\2047925684.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  west_individual_dataframe['Weight'] = west_individual_dataframe['Forecast'] / west_individual_dataframe['Capacity']
C:\Users\prakhar\AppData\Local\Temp\ipykernel_11556\2047925684.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  south_individual_dataframe['Weight'] = south_individual_dataframe['Forecast'] / south_individual_dataframe['Capacity']

In [46]:
east_individual_dataframe.head(27)

   Plant_Name  Forecast  Capacity    Weight
0          E1      45.4       100  0.454000
1          E2      31.2       150  0.208000
2          E3       8.5        50  0.170000
3          E4      88.2       100  0.882000
4          E5      98.4       150  0.656000
5          E6     238.5       300  0.795000
6          E7      66.8       100  0.668000
7          E8     115.4       150  0.769333
8          E9      74.0       100  0.740000
9         E10     156.8       200  0.784000
10        E11     167.9       200  0.839500
11        E12     259.5       500  0.519000
12        E13      79.8       100  0.798000
13        E14      20.9       100  0.209000
14        E15     358.4       400  0.896000
15        E16      69.8       100  0.698000
16        E17      23.4       100  0.234000
17        E18       5.6        50  0.112000
18        E19     144.5       150  0.963333
19        E20     132.8       150  0.885333
20        E21      48.7        50  0.974000
21        E22       9.7        50  0.194000
22        E23      57.6       100  0.576000
23        E24     128.6       150  0.857333

In [47]:


# Calculating the summation of weight for each dataframe
e_weight_sum = east_individual_dataframe['Weight'].sum()
n_weight_sum = north_individual_dataframe['Weight'].sum()
w_weight_sum = west_individual_dataframe['Weight'].sum()
s_weight_sum = south_individual_dataframe['Weight'].sum()

# Calculating the new_forecast for each dataframe
east_individual_dataframe['new_forecast'] = east_individual_dataframe['Weight'] * (zonal_df['forecast'][0] / e_weight_sum)
north_individual_dataframe['new_forecast'] = north_individual_dataframe['Weight'] * (zonal_df['forecast'][1] / n_weight_sum)
west_individual_dataframe['new_forecast'] = west_individual_dataframe['Weight'] * (zonal_df['forecast'][2] / w_weight_sum)
south_individual_dataframe['new_forecast'] = south_individual_dataframe['Weight'] * (zonal_df['forecast'][3] / s_weight_sum)

C:\Users\prakhar\AppData\Local\Temp\ipykernel_11556\1268085397.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  east_individual_dataframe['new_forecast'] = east_individual_dataframe['Weight'] * (zonal_df['forecast'][0] / e_weight_sum)
C:\Users\prakhar\AppData\Local\Temp\ipykernel_11556\1268085397.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  north_individual_dataframe['new_forecast'] = north_individual_dataframe['Weight'] * (zonal_df['forecast'][1] / n_weight_sum)
C:\Users\prakhar\AppData\Local\Temp\ipykernel_11556\1268085397.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  west_individual_dataframe['new_forecast'] = west_individual_dataframe['Weight'] * (zonal_df['forecast'][2] / w_weight_sum)
C:\Users\prakhar\AppData\Local\Temp\ipykernel_11556\1268085397.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  south_individual_dataframe['new_forecast'] = south_individual_dataframe['Weight'] * (zonal_df['forecast'][3] / s_weight_sum)

In [48]:
east_individual_dataframe.head(27)

   Plant_Name  Forecast  Capacity    Weight  new_forecast
0          E1      45.4       100  0.454000     80.080859
1          E2      31.2       150  0.208000     36.689028
2          E3       8.5        50  0.170000     29.986225
3          E4      88.2       100  0.882000    155.575590
4          E5      98.4       150  0.656000    115.711550
5          E6     238.5       300  0.795000    140.229698
6          E7      66.8       100  0.668000    117.828225
7          E8     115.4       150  0.769333    135.702366
8          E9      74.0       100  0.740000    130.528273
9         E10     156.8       200  0.784000    138.289413
10        E11     167.9       200  0.839500    148.079034
11        E12     259.5       500  0.519000     91.546180
12        E13      79.8       100  0.798000    140.758867
13        E14      20.9       100  0.209000     36.865418
14        E15     358.4       400  0.896000    158.045044
15        E16      69.8       100  0.698000    123.119911
16        E17      23.4       100  0.234000     41.275157
17        E18       5.6        50  0.112000     19.755630
18        E19     144.5       150  0.963333    169.921941
19        E20     132.8       150  0.885333    156.163555
20        E21      48.7        50  0.974000    171.803429
21        E22       9.7        50  0.194000     34.219574
22        E23      57.6       100  0.576000    101.600385
23        E24     128.6       150  0.857333    151.224648

In [52]:
south_individual_dataframe['Capacity'].sum()

7950

In [53]:
# Defining a function to calculate the difference between new_forecast and Capacity and replacing negatives with zero
def calculate_difference(row):
    diff = row['new_forecast'] - row['Capacity']
    return max(0, diff)

# Appling the function to each dataframe
east_individual_dataframe['diff_between_new_forecast_and_capacity'] = east_individual_dataframe.apply(calculate_difference, axis=1)
north_individual_dataframe['diff_between_new_forecast_and_capacity'] = north_individual_dataframe.apply(calculate_difference, axis=1)
west_individual_dataframe['diff_between_new_forecast_and_capacity'] = west_individual_dataframe.apply(calculate_difference, axis=1)
south_individual_dataframe['diff_between_new_forecast_and_capacity'] = south_individual_dataframe.apply(calculate_difference, axis=1)

C:\Users\prakhar\AppData\Local\Temp\ipykernel_11556\2262824814.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  east_individual_dataframe['diff_between_new_forecast_and_capacity'] = east_individual_dataframe.apply(calculate_difference, axis=1)
C:\Users\prakhar\AppData\Local\Temp\ipykernel_11556\2262824814.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  north_individual_dataframe['diff_between_new_forecast_and_capacity'] = north_individual_dataframe.apply(calculate_difference, axis=1)
C:\Users\prakhar\AppData\Local\Temp\ipykernel_11556\2262824814.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  west_individual_dataframe['diff_between_new_forecast_and_capacity'] = west_individual_dataframe.apply(calculate_difference, axis=1)
C:\Users\prakhar\AppData\Local\Temp\ipykernel_11556\2262824814.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  south_individual_dataframe['diff_between_new_forecast_and_capacity'] = south_individual_dataframe.apply(calculate_difference, axis=1)

In [55]:
east_individual_dataframe

,Plant_Name,Forecast,Capacity,Weight,new_forecast,diff_between_new_forecast_and_capacity
0,E1,45.4,100,0.454000,80.080859,0.000000
1,E2,31.2,150,0.208000,36.689028,0.000000
2,E3,8.5,50,0.170000,29.986225,0.000000
3,E4,88.2,100,0.882000,155.575590,55.575590
4,E5,98.4,150,0.656000,115.711550,0.000000
5,E6,238.5,300,0.795000,140.229698,0.000000
6,E7,66.8,100,0.668000,117.828225,17.828225
7,E8,115.4,150,0.769333,135.702366,0.000000
8,E9,74.0,100,0.740000,130.528273,30.528273
9,E10,156.8,200,0.784000,138.289413,0.000000
10,E11,167.9,200,0.839500,148.079034,0.000000
11,E12,259.5,500,0.519000,91.546180,0.000000
12,E13,79.8,100,0.798000,140.758867,40.758867
13,E14,20.9,100,0.209000,36.865418,0.000000
14,E15,358.4,400,0.896000,158.045044,0.000000
15,E16,69.8,100,0.698000,123.119911,23.119911
16,E17,23.4,100,0.234000,41.275157,0.000000
17,E18,5.6,50,0.112000,19.755630,0.000000
18,E19,144.5,150,0.963333,169.921941,19.921941
19,E20,132.8,150,0.885333,156.163555,6.163555
20,E21,48.7,50,0.974000,171.803429,121.803429
21,E22,9.7,50,0.194000,34.219574,0.000000
22,E23,57.6,100,0.576000,101.600385,1.600385
23,E24,128.6,150,0.857333,151.224648,1.224648

In [57]:
# Now we have to distribute the total exceeding new_forecast into the wind farms whose new_forecast does not exceed capacity
# For this we are calculating the total exceeding new_forecasts first
east_exceeded_forecast = east_individual_dataframe['diff_between_new_forecast_and_capacity'].sum()
north_exceeded_forecast = north_individual_dataframe['diff_between_new_forecast_and_capacity'].sum()
west_exceeded_forecast = west_individual_dataframe['diff_between_new_forecast_and_capacity'].sum()
south_exceeded_forecast = south_individual_dataframe['diff_between_new_forecast_and_capacity'].sum()

In [60]:
# For each of the zones we are calculating the sum of weights of wind farms being considered for distribution of exceeding new forecasts

# For 'East' dataframe
sum_weights_e_less_than_capacity = east_individual_dataframe.loc[east_individual_dataframe['new_forecast'] < east_individual_dataframe['Capacity'], 'Weight'].sum()

# For 'North' dataframe
sum_weights_n_less_than_capacity = north_individual_dataframe.loc[north_individual_dataframe['new_forecast'] < north_individual_dataframe['Capacity'], 'Weight'].sum()

# For 'West' dataframe
sum_weights_w_less_than_capacity = west_individual_dataframe.loc[west_individual_dataframe['new_forecast'] < west_individual_dataframe['Capacity'], 'Weight'].sum()

# For 'South' dataframe
sum_weights_s_less_than_capacity = south_individual_dataframe.loc[south_individual_dataframe['new_forecast'] < south_individual_dataframe['Capacity'], 'Weight'].sum()

In [65]:
# Distributing the exceeding forecast among the valid wind farms in east zone
east_individual_dataframe['new_forecast'] = east_individual_dataframe.apply(lambda row: row['new_forecast'] + (row['Weight'] * east_exceeded_forecast / sum_weights_e_less_than_capacity) if row['new_forecast'] < row['Capacity'] else row['Capacity'], axis=1)

C:\Users\prakhar\AppData\Local\Temp\ipykernel_11556\3181943741.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  east_individual_dataframe['new_forecast'] = east_individual_dataframe.apply(lambda row: row['new_forecast'] + (row['Weight'] * east_exceeded_forecast / sum_weights_e_less_than_capacity) if row['new_forecast'] < row['Capacity'] else row['Capacity'], axis=1)

In [66]:
east_individual_dataframe.head(27)

,Plant_Name,Forecast,Capacity,Weight,new_forecast,diff_between_new_forecast_and_capacity
0,E1,45.4,100,0.454000,100.000000,0.000000
1,E2,31.2,150,0.208000,56.061770,0.000000
2,E3,8.5,50,0.170000,45.819716,0.000000
3,E4,88.2,100,0.882000,100.000000,55.575590
4,E5,98.4,150,0.656000,176.810198,0.000000
5,E6,238.5,300,0.795000,214.274554,0.000000
6,E7,66.8,100,0.668000,100.000000,17.828225
7,E8,115.4,150,0.769333,150.000000,0.000000
8,E9,74.0,100,0.740000,100.000000,30.528273
9,E10,156.8,200,0.784000,211.309749,0.000000
10,E11,167.9,200,0.839500,226.268538,0.000000
11,E12,259.5,500,0.519000,139.884897,0.000000
12,E13,79.8,100,0.798000,100.000000,40.758867
13,E14,20.9,100,0.209000,56.331298,0.000000
14,E15,358.4,400,0.896000,241.496855,0.000000
15,E16,69.8,100,0.698000,100.000000,23.119911
16,E17,23.4,100,0.234000,63.069491,0.000000
17,E18,5.6,50,0.112000,30.187107,0.000000
18,E19,144.5,150,0.963333,150.000000,19.921941
19,E20,132.8,150,0.885333,150.000000,6.163555
20,E21,48.7,50,0.974000,50.000000,121.803429
21,E22,9.7,50,0.194000,52.288382,0.000000
22,E23,57.6,100,0.576000,100.000000,1.600385
23,E24,128.6,150,0.857333,150.000000,1.224648

In [67]:
# Distributing the exceeding forecast among the valid wind farms in north, south and west zones respectively

north_individual_dataframe['new_forecast'] = north_individual_dataframe.apply(lambda row: row['new_forecast'] + (row['Weight'] * north_exceeded_forecast / sum_weights_n_less_than_capacity) if row['new_forecast'] < row['Capacity'] else row['Capacity'], axis=1)
west_individual_dataframe['new_forecast'] = west_individual_dataframe.apply(lambda row: row['new_forecast'] + (row['Weight'] * west_exceeded_forecast / sum_weights_w_less_than_capacity) if row['new_forecast'] < row['Capacity'] else row['Capacity'], axis=1)
south_individual_dataframe['new_forecast'] = south_individual_dataframe.apply(lambda row: row['new_forecast'] + (row['Weight'] * south_exceeded_forecast / sum_weights_s_less_than_capacity) if row['new_forecast'] < row['Capacity'] else row['Capacity'], axis=1)

C:\Users\prakhar\AppData\Local\Temp\ipykernel_11556\1612065220.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  north_individual_dataframe['new_forecast'] = north_individual_dataframe.apply(lambda row: row['new_forecast'] + (row['Weight'] * north_exceeded_forecast / sum_weights_n_less_than_capacity) if row['new_forecast'] < row['Capacity'] else row['Capacity'], axis=1)
C:\Users\prakhar\AppData\Local\Temp\ipykernel_11556\1612065220.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  west_individual_dataframe['new_forecast'] = west_individual_dataframe.apply(lambda row: row['new_forecast'] + (row['Weight'] * west_exceeded_forecast / sum_weights_w_less_than_capacity) if row['new_forecast'] < row['Capacity'] else row['Capacity'], axis=1)
C:\Users\prakhar\AppData\Local\Temp\ipykernel_11556\1612065220.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  south_individual_dataframe['new_forecast'] = south_individual_dataframe.apply(lambda row: row['new_forecast'] + (row['Weight'] * south_exceeded_forecast / sum_weights_s_less_than_capacity) if row['new_forecast'] < row['Capacity'] else row['Capacity'], axis=1)

In [68]:
# Checking if there exist any wind farm whose new_forecast is greater than the capacity. 
# If found any, we will apply the same process as applied above to distribute the exceeding weights.
east_individual_dataframe['diff_between_new_forecast_and_capacity'] = east_individual_dataframe.apply(calculate_difference, axis=1)
north_individual_dataframe['diff_between_new_forecast_and_capacity'] = north_individual_dataframe.apply(calculate_difference, axis=1)
west_individual_dataframe['diff_between_new_forecast_and_capacity'] = west_individual_dataframe.apply(calculate_difference, axis=1)
south_individual_dataframe['diff_between_new_forecast_and_capacity'] = south_individual_dataframe.apply(calculate_difference, axis=1)

C:\Users\prakhar\AppData\Local\Temp\ipykernel_11556\735359072.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  east_individual_dataframe['diff_between_new_forecast_and_capacity'] = east_individual_dataframe.apply(calculate_difference, axis=1)
C:\Users\prakhar\AppData\Local\Temp\ipykernel_11556\735359072.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  north_individual_dataframe['diff_between_new_forecast_and_capacity'] = north_individual_dataframe.apply(calculate_difference, axis=1)
C:\Users\prakhar\AppData\Local\Temp\ipykernel_11556\735359072.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  west_individual_dataframe['diff_between_new_forecast_and_capacity'] = west_individual_dataframe.apply(calculate_difference, axis=1)
C:\Users\prakhar\AppData\Local\Temp\ipykernel_11556\735359072.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  south_individual_dataframe['diff_between_new_forecast_and_capacity'] = south_individual_dataframe.apply(calculate_difference, axis=1)

In [70]:
east_individual_dataframe.head(27)

,Plant_Name,Forecast,Capacity,Weight,new_forecast,diff_between_new_forecast_and_capacity
0,E1,45.4,100,0.454000,100.000000,0.000000
1,E2,31.2,150,0.208000,56.061770,0.000000
2,E3,8.5,50,0.170000,45.819716,0.000000
3,E4,88.2,100,0.882000,100.000000,0.000000
4,E5,98.4,150,0.656000,176.810198,26.810198
5,E6,238.5,300,0.795000,214.274554,0.000000
6,E7,66.8,100,0.668000,100.000000,0.000000
7,E8,115.4,150,0.769333,150.000000,0.000000
8,E9,74.0,100,0.740000,100.000000,0.000000
9,E10,156.8,200,0.784000,211.309749,11.309749
10,E11,167.9,200,0.839500,226.268538,26.268538
11,E12,259.5,500,0.519000,139.884897,0.000000
12,E13,79.8,100,0.798000,100.000000,0.000000
13,E14,20.9,100,0.209000,56.331298,0.000000
14,E15,358.4,400,0.896000,241.496855,0.000000
15,E16,69.8,100,0.698000,100.000000,0.000000
16,E17,23.4,100,0.234000,63.069491,0.000000
17,E18,5.6,50,0.112000,30.187107,0.000000
18,E19,144.5,150,0.963333,150.000000,0.000000
19,E20,132.8,150,0.885333,150.000000,0.000000
20,E21,48.7,50,0.974000,50.000000,0.000000
21,E22,9.7,50,0.194000,52.288382,2.288382
22,E23,57.6,100,0.576000,100.000000,0.000000
23,E24,128.6,150,0.857333,150.000000,0.000000

In [71]:
east_exceeded_forecast = east_individual_dataframe['diff_between_new_forecast_and_capacity'].sum()
north_exceeded_forecast = north_individual_dataframe['diff_between_new_forecast_and_capacity'].sum()
west_exceeded_forecast = west_individual_dataframe['diff_between_new_forecast_and_capacity'].sum()
south_exceeded_forecast = south_individual_dataframe['diff_between_new_forecast_and_capacity'].sum()

In [72]:
# For 'East' dataframe
sum_weights_e_less_than_capacity = east_individual_dataframe.loc[east_individual_dataframe['new_forecast'] < east_individual_dataframe['Capacity'], 'Weight'].sum()

# For 'North' dataframe
sum_weights_n_less_than_capacity = north_individual_dataframe.loc[north_individual_dataframe['new_forecast'] < north_individual_dataframe['Capacity'], 'Weight'].sum()

# For 'West' dataframe
sum_weights_w_less_than_capacity = west_individual_dataframe.loc[west_individual_dataframe['new_forecast'] < west_individual_dataframe['Capacity'], 'Weight'].sum()

# For 'South' dataframe
sum_weights_s_less_than_capacity = south_individual_dataframe.loc[south_individual_dataframe['new_forecast'] < south_individual_dataframe['Capacity'], 'Weight'].sum()

In [73]:
east_individual_dataframe['new_forecast'] = east_individual_dataframe.apply(lambda row: row['new_forecast'] + (row['Weight'] * east_exceeded_forecast / sum_weights_e_less_than_capacity) if row['new_forecast'] < row['Capacity'] else row['Capacity'], axis=1)
north_individual_dataframe['new_forecast'] = north_individual_dataframe.apply(lambda row: row['new_forecast'] + (row['Weight'] * north_exceeded_forecast / sum_weights_n_less_than_capacity) if row['new_forecast'] < row['Capacity'] else row['Capacity'], axis=1)
west_individual_dataframe['new_forecast'] = west_individual_dataframe.apply(lambda row: row['new_forecast'] + (row['Weight'] * west_exceeded_forecast / sum_weights_w_less_than_capacity) if row['new_forecast'] < row['Capacity'] else row['Capacity'], axis=1)
south_individual_dataframe['new_forecast'] = south_individual_dataframe.apply(lambda row: row['new_forecast'] + (row['Weight'] * south_exceeded_forecast / sum_weights_s_less_than_capacity) if row['new_forecast'] < row['Capacity'] else row['Capacity'], axis=1)

C:\Users\prakhar\AppData\Local\Temp\ipykernel_11556\3691086564.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  east_individual_dataframe['new_forecast'] = east_individual_dataframe.apply(lambda row: row['new_forecast'] + (row['Weight'] * east_exceeded_forecast / sum_weights_e_less_than_capacity) if row['new_forecast'] < row['Capacity'] else row['Capacity'], axis=1)
C:\Users\prakhar\AppData\Local\Temp\ipykernel_11556\3691086564.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  north_individual_dataframe['new_forecast'] = north_individual_dataframe.apply(lambda row: row['new_forecast'] + (row['Weight'] * north_exceeded_forecast / sum_weights_n_less_than_capacity) if row['new_forecast'] < row['Capacity'] else row['Capacity'], axis=1)
C:\Users\prakhar\AppData\Local\Temp\ipykernel_11556\3691086564.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  west_individual_dataframe['new_forecast'] = west_individual_dataframe.apply(lambda row: row['new_forecast'] + (row['Weight'] * west_exceeded_forecast / sum_weights_w_less_than_capacity) if row['new_forecast'] < row['Capacity'] else row['Capacity'], axis=1)
C:\Users\prakhar\AppData\Local\Temp\ipykernel_11556\3691086564.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  south_individual_dataframe['new_forecast'] = south_individual_dataframe.apply(lambda row: row['new_forecast'] + (row['Weight'] * south_exceeded_forecast / sum_weights_s_less_than_capacity) if row['new_forecast'] < row['Capacity'] else row['Capacity'], axis=1)

In [75]:
east_individual_dataframe.head(27)

,Plant_Name,Forecast,Capacity,Weight,new_forecast,diff_between_new_forecast_and_capacity
0,E1,45.4,100,0.454000,100.000000,0.000000
1,E2,31.2,150,0.208000,60.474366,0.000000
2,E3,8.5,50,0.170000,49.426164,0.000000
3,E4,88.2,100,0.882000,100.000000,0.000000
4,E5,98.4,150,0.656000,150.000000,26.810198
5,E6,238.5,300,0.795000,231.140003,0.000000
6,E7,66.8,100,0.668000,100.000000,0.000000
7,E8,115.4,150,0.769333,150.000000,0.000000
8,E9,74.0,100,0.740000,100.000000,0.000000
9,E10,156.8,200,0.784000,200.000000,11.309749
10,E11,167.9,200,0.839500,200.000000,26.268538
11,E12,259.5,500,0.519000,150.895172,0.000000
12,E13,79.8,100,0.798000,100.000000,0.000000
13,E14,20.9,100,0.209000,60.765108,0.000000
14,E15,358.4,400,0.896000,260.504960,0.000000
15,E16,69.8,100,0.698000,100.000000,0.000000
16,E17,23.4,100,0.234000,68.033661,0.000000
17,E18,5.6,50,0.112000,32.563120,0.000000
18,E19,144.5,150,0.963333,150.000000,0.000000
19,E20,132.8,150,0.885333,150.000000,0.000000
20,E21,48.7,50,0.974000,50.000000,0.000000
21,E22,9.7,50,0.194000,50.000000,2.288382
22,E23,57.6,100,0.576000,100.000000,0.000000
23,E24,128.6,150,0.857333,150.000000,0.000000

In [76]:
east_individual_dataframe['diff_between_new_forecast_and_capacity'] = east_individual_dataframe.apply(calculate_difference, axis=1)
north_individual_dataframe['diff_between_new_forecast_and_capacity'] = north_individual_dataframe.apply(calculate_difference, axis=1)
west_individual_dataframe['diff_between_new_forecast_and_capacity'] = west_individual_dataframe.apply(calculate_difference, axis=1)
south_individual_dataframe['diff_between_new_forecast_and_capacity'] = south_individual_dataframe.apply(calculate_difference, axis=1)

C:\Users\prakhar\AppData\Local\Temp\ipykernel_11556\735359072.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  east_individual_dataframe['diff_between_new_forecast_and_capacity'] = east_individual_dataframe.apply(calculate_difference, axis=1)
C:\Users\prakhar\AppData\Local\Temp\ipykernel_11556\735359072.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  north_individual_dataframe['diff_between_new_forecast_and_capacity'] = north_individual_dataframe.apply(calculate_difference, axis=1)
C:\Users\prakhar\AppData\Local\Temp\ipykernel_11556\735359072.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  west_individual_dataframe['diff_between_new_forecast_and_capacity'] = west_individual_dataframe.apply(calculate_difference, axis=1)
C:\Users\prakhar\AppData\Local\Temp\ipykernel_11556\735359072.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  south_individual_dataframe['diff_between_new_forecast_and_capacity'] = south_individual_dataframe.apply(calculate_difference, axis=1)

In [81]:
west_individual_dataframe.head(27)

,Plant_Name,Forecast,Capacity,Weight,new_forecast,diff_between_new_forecast_and_capacity
50,W1,221.6,250,0.886400,250.000000,0.000000
51,W2,77.6,100,0.776000,100.000000,0.000000
52,W3,86.6,150,0.577333,150.000000,0.000000
53,W4,94.8,150,0.632000,150.000000,0.000000
54,W5,99.0,200,0.495000,206.524368,6.524368
55,W6,47.6,100,0.476000,100.000000,0.000000
56,W7,11.4,100,0.114000,47.563188,0.000000
57,W8,9.4,50,0.188000,50.000000,0.000000
58,W9,35.0,150,0.233333,97.351554,0.000000
59,W10,35.3,100,0.353000,100.000000,0.000000
60,W11,44.3,150,0.295333,123.219253,0.000000
61,W12,119.3,200,0.596500,200.000000,0.000000
62,W13,36.7,50,0.734000,50.000000,0.000000
63,W14,69.2,150,0.461333,150.000000,0.000000
64,W15,48.1,200,0.240500,100.341637,0.000000

In [88]:
west_exceeded_forecast = west_individual_dataframe['diff_between_new_forecast_and_capacity'].sum()
sum_weights_w_less_than_capacity = west_individual_dataframe.loc[west_individual_dataframe['new_forecast'] < west_individual_dataframe['Capacity'], 'Weight'].sum()
west_individual_dataframe['new_forecast'] = west_individual_dataframe.apply(lambda row: row['new_forecast'] + (row['Weight'] * west_exceeded_forecast / sum_weights_w_less_than_capacity) if row['new_forecast'] < row['Capacity'] else row['Capacity'], axis=1)

C:\Users\prakhar\AppData\Local\Temp\ipykernel_11556\123446975.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  west_individual_dataframe['new_forecast'] = west_individual_dataframe.apply(lambda row: row['new_forecast'] + (row['Weight'] * west_exceeded_forecast / sum_weights_w_less_than_capacity) if row['new_forecast'] < row['Capacity'] else row['Capacity'], axis=1)

In [89]:
west_individual_dataframe.head(27)

,Plant_Name,Forecast,Capacity,Weight,new_forecast,diff_between_new_forecast_and_capacity
50,W1,221.6,250,0.886400,250.000000,0.000000
51,W2,77.6,100,0.776000,100.000000,0.000000
52,W3,86.6,150,0.577333,150.000000,0.000000
53,W4,94.8,150,0.632000,150.000000,0.000000
54,W5,99.0,200,0.495000,200.000000,0.000000
55,W6,47.6,100,0.476000,100.000000,0.000000
56,W7,11.4,100,0.114000,62.216775,0.000000
57,W8,9.4,50,0.188000,50.000000,0.000000
58,W9,35.0,150,0.233333,127.344277,0.000000
59,W10,35.3,100,0.353000,100.000000,0.000000
60,W11,44.3,150,0.295333,150.000000,7.442357
61,W12,119.3,200,0.596500,200.000000,0.000000
62,W13,36.7,50,0.734000,50.000000,0.000000
63,W14,69.2,150,0.461333,150.000000,0.000000
64,W15,48.1,200,0.240500,131.255566,0.000000

In [90]:
west_individual_dataframe['diff_between_new_forecast_and_capacity'] = west_individual_dataframe.apply(calculate_difference, axis=1)

C:\Users\prakhar\AppData\Local\Temp\ipykernel_11556\2900085387.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  west_individual_dataframe['diff_between_new_forecast_and_capacity'] = west_individual_dataframe.apply(calculate_difference, axis=1)

In [100]:
west_individual_dataframe

,Plant_Name,Forecast,Capacity,Weight,new_forecast,diff_between_new_forecast_and_capacity
50,W1,221.6,250,0.886400,250.000000,0
51,W2,77.6,100,0.776000,100.000000,0
52,W3,86.6,150,0.577333,150.000000,0
53,W4,94.8,150,0.632000,150.000000,0
54,W5,99.0,200,0.495000,200.000000,0
55,W6,47.6,100,0.476000,100.000000,0
56,W7,11.4,100,0.114000,62.216775,0
57,W8,9.4,50,0.188000,50.000000,0
58,W9,35.0,150,0.233333,127.344277,0
59,W10,35.3,100,0.353000,100.000000,0
60,W11,44.3,150,0.295333,150.000000,0
61,W12,119.3,200,0.596500,200.000000,0
62,W13,36.7,50,0.734000,50.000000,0
63,W14,69.2,150,0.461333,150.000000,0
64,W15,48.1,200,0.240500,131.255566,0

Finally, we distributed the weights among all the zones and for none of the distribution the new_forecast is greater than the capacity. So we are concatinating the Plant_Name and new_forecast to get the desired output.

In [98]:
# Concatenate the four dataframes into one
merged_dataframe = pd.concat([east_individual_dataframe, north_individual_dataframe, west_individual_dataframe, south_individual_dataframe])

# Select only the 'Plant_Name' and 'new_forecast' columns
merged_dataframe = merged_dataframe[['Plant_Name', 'new_forecast']]

# Rename the 'new_forecast' column to 'forecast'
merged_dataframe.rename(columns={'new_forecast': 'Forecast'}, inplace=True)

# Save the merged dataframe to a CSV file
merged_dataframe.to_csv('merged_data.csv', index=False)

Required Output

In [99]:
merged_dataframe.head(100)

   Plant_Name    Forecast
0          E1  100.000000
1          E2   60.474366
2          E3   49.426164
3          E4  100.000000
4          E5  150.000000
..        ...         ...
95        S31  213.936942
96        S32  150.000000
97        S33  200.000000
98        S34   50.000000
99        S35  302.681467

[100 rows x 2 columns]